#!/bin/sh

spotdl https://open.spotify.com/track/
spotdl https://open.spotify.com/track/
spotdl https://open.spotify.com/track/
spotdl https://open.spotify.com/track/
spotdl https://open.spotify.com/track/
spotdl https://open.spotify.com/track/
spotdl https://open.spotify.com/track/
